# Quick boot options
sudo: false
cache:
  directories:
    - node_modules

# Ignore version tags
branches:
  except:
    - /^v[0-9]/

# Language options
language: node_js
node_js:
  - '0.10'

env:
  global:
    # COVERALLS_REPO_TOKEN
    - secure: G1adA1VnCTliMYMy5zXNYx4tYEi6Zbwr9x1iP3azoQLUa3GHTfxyu594C5wHig4fd/xcb7ZtWPvYXUXXZKMIjAH/1njQOdEBSMTUFM6JVSCHNYzK1goBsIF4w1pP0Q92az5DvUGaWNZ0P1Ri/4uh60CpDoX7YZWRIM4VS80gFHkEFzF8ErmnwnJW3b5VEDpLhDcSuZQjJAIWA3mdGXPXMyZy91uSRkcUN+8sK6Bw1/A+gntcamcfSLA7dcgDL2Aqi7+DjLrTCEQmN5UexLfruA0Tdb1tuoqhGX4kEB5xXKmT6n3AyCGaClLvxUkCLZYJTSirJ7X5RzP8wiJQC7RmB86c9TvMAYBXAPql+4wf8mHMaL8mAx4KGq6rtlrtG7sZqSCfMIr0jwX4GmkeTQB17c0Q2R0U5aCQq0B/DzxzlKAegQ+a2MXFCtdMJwJFnhznH2Jh4G2WFodtICYxkLZMX64MQ1aWEs30JLZ0IRzhOQgyIEDNALm+73Tn5jdC3QovjmKGkZivPnRbl8MHGozJ7tjRn2cB88vgAXBZWA47L0dktMs5IDqeN7fm4yf7ay3Y/3fdlc6unEwb9yICFtKo80LbVGSh9qayWyPFkYuwDZ28Tbiy5WhimIcq7EfWHbkHUki/GOj0gRFY/eJmgjR3A2/O0FftoFKdixDzj8fTOM0=
    # SAUCE_TOKENS
    - secure: gShPJ1j3PGJKKTWQKvLZgoarlz7WpnmUYqaPbCfxALxGTO0wfJQWDculUlO4wKw1L3ELh3XDAvwhzrbFYJQuf7+gC3h9GDMxWHMUj5iJVAmnL8D4pVbZP9Mtbv/RNJs7NLkNok4HIhd/AAWT1uyXZ7Rj8nVJFyfFDpTU+JnJXJiZaCD3pQvM52VCQKZE2s7DHacsjGEdreO7HlagLfQ1Ax/9PNHX2Fz+H2unnQIOYYdTlArtdCfwYkEUSwRx25GPp8iBbA/b/rVNz3Bi0Ua281rITAJMu/7pr6Zt1HUgGlNVsBmq/t+xXDmOz14vgWQMwlZ49x2ySQbtGNkJ8sp0mBz2YUrdBvkGSHDBpaCxPnCTsLfxGRjNhUtkmwrwLf0Omrtua7+d+3g7r0JcCAgfQEqpXqh9JOLUltLQyrrLJkqyklBBjnXh4wqDiReGveL2alX92Q8CchfbuJlJNZ4nofRZcnziopQUfs9zjg4w3FYUxwTDcC07n6VVpCwc0qL7PtXlfHQlgRFTkCJbqzGGkNXGN3tneyycb6YlNmhS0XVyqxuSxFrueL8Gy74YTVgJkiUcam0r0ICYYZr+q9i/wtwZz7p0n690ZkQtSldGwug87iT5esFjE/xMVsxRWuOOEMlqE+1Cu6Yg/1y3H7f0nfIIL4Fx4dxiLFt+bAr6o3A=
    - secure: NBH/n8PyOLt+puLBg8oBV8pJ7p0dAS7hh02ibPTUoWICpyUe4nva03dZodn9BJythOyn6qyscaZgp45bsxI3zq3VJk+tDpnNtTJC43dud7KE5oGOvaD3UypdRPuNZyytP86owkH1h77HQ0DTTm1rT5rFcfWwI8jE5uALwNC1FK67LhZsMlWBjRz3qyp4Q6IRFLZCCvH/vT3rwhRlkEffwyqKbbUCHy2wU00A3TfvDCvVOh2yIoqnVX/OXLxaVntG8pZZJdgKgIcV93YZ53saLhfB7CFl52ABzzepD1jx9KlN2f4toeqbc+4n4jxIS2yvPV29lbc6BzxcVRtlWwRVOTYP2L226jtWBNv+eJzjAfalFESri9PjynRyr+ge1taNX377ztT4ETKJRPTHhUfNhM88f70y/IsANkIa86IK1V0XfHO1YhVlQGKCSm/58c98BHj0yoJLPMfmLikGeYXb+r6kWuLyE/S2ijH6PEOAKdsD+SOn+3NQKmvDruwdUhDjF1qNcJC2Y2hnctz/5gRJxnuO1ywCL6WnFIEj7ke3NYcKpLukeiM8DsG0uhvCFnGRtPFpsw3bwZvI83a2Sx3Rn2n8qRbIVZob6sU/2SVfHjoIRhh1T+rwNTa3dOy7QNJximw/pHtjBsnYNJlbiccyLIcDE206zJqnVb3+/sRHZWE=

# Npm publish options
before_deploy:
  - npm install coffee-script --global
deploy:
  provider: npm
  email: i59naga@icloud.com
  api_key:
    secure: ABLoz5wDMB1imnwmQLWlTXz5qS8qPYgAu5zWt9tOi2urDJQhCQf9Bi8Cg5LqLh433sL8qMOEkUDFvqVNl5ZPbHYki8hFpZF2/kW51vdIxayBjMRU9IgRBMD30BinwXFvzBwBwv+64ohWXGH2VsYMM47k6RIXvKRqvaSo38wqVIOG9qAEcmnpw53ESWemNHoZQf0+WK0pvejNZtlQGE3DzPv8vbcLR0paV0mhOlCfWFpUYrI2cW7KzY3l86O5lpeIBDqrc6hA1Zncvzb2ytsIoe4PV6v4BKZ0NOM8KvKIkhyEbmK/Vrx+9/CEStMJ+ieHLwawA5kWcqjcRQjCB7t/LVqb9ZPlLKVCEOg43IlilmdwL54VMxXbreVnqjFA6VQIIKCiMipIah5MeEUQksPEWsYH9feTkd6q2kN06dz5ydl6EwNB2Zz1X8dyIAs5T6BSlayuZ8Isau1VwjKBxuNYam79616yoYj6bflwKLlyhq6KbFVuGD2Gyt+rGGdTx+I1L6W6EmlrTUfV7tQWeqSP41KLXa0ZVomyV/m+vsdzPnb0CRJ8HgsDUESN+73zA5vjl/IAaqA3bQaXmi9MzL9r7Q6ep3XAi0V1UjvhwaVjSSx+T9MK35U+VIxlaMqX+k/0bFr3n3F0fTdF+J7YNO8Vhiu+XDw7HQsrCd8vHwrfdBg=
